#cloud-config
vyos_config_commands:
  # Rack1 Networks
  - set interfaces ethernet eth0 address '172.16.100.1/24'
  - set interfaces ethernet eth0 address '172.16.101.1/24'
  - set interfaces ethernet eth0 address '172.16.102.1/24'
  - set interfaces ethernet eth0 address '172.16.103.1/24'
  - set interfaces ethernet eth0 address '172.16.104.1/24'
  - set interfaces ethernet eth0 address '172.16.105.1/24'
  - set interfaces ethernet eth0 address '172.16.106.1/24'
  - set interfaces ethernet eth0 address '172.16.107.1/24'
  #
  - set protocols bgp 65000 address-family 'ipv4-unicast'
  - set protocols bgp 65000 address-family network '0.0.0.0/0'
  #
  - set protocols bgp 65000 neighbor 172.16.106.10 remote-as '65010'
  - set protocols bgp 65000 neighbor 172.16.106.10 timers keepalive '4'
  - set protocols bgp 65000 neighbor 172.16.106.10 timers holdtime '12'
  - set protocols bgp 65000 neighbor 172.16.106.10 password 'VMware1!'
  #
  - set protocols bgp 65000 neighbor 172.16.106.11 remote-as '65010'
  - set protocols bgp 65000 neighbor 172.16.106.11 timers keepalive '4'
  - set protocols bgp 65000 neighbor 172.16.106.11 timers holdtime '12'
  - set protocols bgp 65000 neighbor 172.16.106.11 password 'VMware1!'
  #
  - set protocols bgp 65000 neighbor 172.16.107.10 remote-as '65010'
  - set protocols bgp 65000 neighbor 172.16.107.10 timers keepalive '4'
  - set protocols bgp 65000 neighbor 172.16.107.10 timers holdtime '12'
  - set protocols bgp 65000 neighbor 172.16.107.10 password 'VMware1!'
  #
  - set protocols bgp 65000 neighbor 172.16.107.11 remote-as '65010'
  - set protocols bgp 65000 neighbor 172.16.107.11 timers keepalive '4'
  - set protocols bgp 65000 neighbor 172.16.107.11 timers holdtime '12'
  - set protocols bgp 65000 neighbor 172.16.107.11 password 'VMware1!'